name: Eglot check

on:
  push:
    branches: [github-action]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '26.3'
          - '27.1'
          - 'snapshot'

    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/setup-python@v2
    - run: |
        python -m pip install --upgrade pip
        pip install python-language-server[all]==0.31.10
    - run: make eglot-check
